import type { Feed, FeedItem } from './types.js';

export function renderHtml(feed: Feed, items: FeedItem[], options: { maxItems?: number; theme?: 'light' | 'dark' | 'auto'; includeContent?: boolean } = {}): string {
  const maxItems = options.maxItems || items.length;
  const theme = options.theme || 'auto';
  const includeContent = options.includeContent !== false;

  const bgColor = theme === 'dark' ? '#1a1a2e' : theme === 'light' ? '#ffffff' : '';
  const textColor = theme === 'dark' ? '#e0e0e0' : theme === 'light' ? '#333333' : '';
  const cardBg = theme === 'dark' ? '#16213e' : theme === 'light' ? '#f8f9fa' : '';
  const borderColor = theme === 'dark' ? '#0f3460' : theme === 'light' ? '#dee2e6' : '';

  const style = `
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; background: ${bgColor}; color: ${textColor}; }
    .header { border-bottom: 2px solid ${borderColor}; padding-bottom: 20px; margin-bottom: 30px; }
    .header h1 { margin: 0 0 10px 0; }
    .header .meta { color: #666; font-size: 14px; }
    .item { border: 1px solid ${borderColor}; border-radius: 8px; padding: 20px; margin-bottom: 20px; background: ${cardBg}; }
    .item h2 { margin: 0 0 10px 0; font-size: 18px; }
    .item h2 a { color: inherit; text-decoration: none; }
    .item h2 a:hover { text-decoration: underline; }
    .item .meta { color: #666; font-size: 13px; margin-bottom: 10px; }
    .item .description { line-height: 1.6; }
    .item .tags { margin-top: 10px; }
    .item .tag { display: inline-block; background: #e9ecef; color: #495057; padding: 2px 8px; border-radius: 4px; font-size: 12px; margin-right: 5px; }
    .item img { max-width: 100%; border-radius: 4px; margin: 10px 0; }
    .content { margin-top: 15px; padding-top: 15px; border-top: 1px solid ${borderColor}; }
    footer { text-align: center; color: #666; font-size: 12px; margin-top: 40px; }
  `;

  const itemsHtml = items.slice(0, maxItems).map(item => {
    const imageHtml = item.image ? `<img src="${escapeAttr(item.image)}" alt="${escapeAttr(item.title)}" loading="lazy"/>` : '';
    const tagsHtml = item.tags.length > 0
      ? `<div class="tags">${item.tags.map(t => `<span class="tag">${escapeHtml(t)}</span>`).join('')}</div>`
      : '';
    const contentHtml = includeContent && item.content && item.content !== item.description
      ? `<div class="content">${item.content}</div>`
      : '';

    return `
    <div class="item">
      <h2><a href="${escapeAttr(item.link)}" target="_blank">${escapeHtml(item.title)}</a></h2>
      <div class="meta">
        ${item.author ? `<span>${escapeHtml(item.author)}</span> · ` : ''}
        ${item.published ? `<span>${formatDate(item.published)}</span>` : ''}
      </div>
      ${imageHtml}
      <div class="description">${escapeHtml(item.description)}</div>
      ${tagsHtml}
      ${contentHtml}
    </div>`;
  }).join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>${escapeHtml(feed.title)}</title>
  <style>${style}</style>
</head>
<body>
  <div class="header">
    <h1>${escapeHtml(feed.title)}</h1>
    <div class="meta">${escapeHtml(feed.description)} · ${items.length} items</div>
  </div>
  ${itemsHtml}
  <footer>Generated by nuref</footer>
</body>
</html>`;
}

export function renderItemHtml(item: FeedItem): string {
  return `
    <div class="item">
      <h2><a href="${escapeAttr(item.link)}" target="_blank">${escapeHtml(item.title)}</a></h2>
      <div class="meta">
        ${item.author ? `<span>${escapeHtml(item.author)}</span> · ` : ''}
        ${item.published ? `<span>${formatDate(item.published)}</span>` : ''}
      </div>
      <div class="description">${escapeHtml(item.description)}</div>
      ${item.content ? `<div class="content">${item.content}</div>` : ''}
    </div>`;
}

function escapeHtml(str: string): string {
  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function escapeAttr(str: string): string {
  return str.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function formatDate(dateStr: string): string {
  try {
    const date = new Date(dateStr);
    return date.toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
  } catch {
    return dateStr;
  }
}
